### ISSUE TITLE
Empty dsk2ascii output for higher kmers

### ISSUE THREAD

**Issue by codemeleon** [GATB/dsk#11]
Hi,
I am trying to generate kmer for ~8Kb fasta file using following commands

```
dsk -kmer-size 30 -file test.fasta -out test
dsk2ascii -file test.h5 -out test.txt
```
The output file `test.txt` is empty.  However, for kmer size 15, it generates only 17 Kmers (each counts 2).

Could you please let me know what could I be doing wrong? Input file is attached.

Thank you.

[test.fasta.gz](https://github.com/GATB/dsk/files/4621535/test.fasta.gz)

**Comment by rchikhi** [comment]
Hi, by default DSK filters out all kmers seen only once, which is what you dataset contains. Please use the ` -abundance-min 1` to list all kmers including those seen just once. Sorry for the late response.
