### ISSUE TITLE
dsk crashes if the read length is greater than 8192

### ISSUE THREAD

**Issue by tbenavi1** [GATB/dsk#12]
Hello,

I am trying to run dsk on a fasta file with long reads (e.g. > 10,000 bp). However, I get the following error:

EXCEPTION: Unable to open bank 'reads.fasta' (if it is a list of files, perhaps some of the files inside don't exist)

After running some tests with simulated fasta files, I have determined that dsk runs fine with read lengths up to 8192 (2^13) but starts to fail when the reads exceed 8192.

Am I doing something wrong? Thanks for letting me know.

**Comment by tbenavi1** [comment]
Additionally, dsk fails if the read name (including '>') is greater than 255 characters.

**Comment by rchikhi** [comment]
Hi Timothy,

DSK has been tested on complete genomes, so in principle it should work with > 10,000 bp sequences. I just tested it on a 4 Mbp sequence and it worked.. What was your command line, and can you please paste the first 100 characters of the input fasta file?

Regarding long read names, this is indeed a known (and rare) bug, a workaround is to rename the input files, e.g. using https://www.biostars.org/p/226111/#226114

Rayan

**Comment by tbenavi1** [comment]
Thanks for the response. I believe the problem for me was actually the long read name.
