### ISSUE TITLE
GTAB HDF5 problem version

### ISSUE THREAD

**Issue by lufuhao** [GATB/dsk#13]
System ubuntu20 gcc 9.3.0

Problem: running problem

Describe: compiling was successful, but error was reported when running to DSK program

error log
-------------------------------------------
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /home/hpcsoft/ProdSoft/dsk/v2.3.3-68b79e4/x86_64/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 425 in H5Aopen(): unable to load attribute info from object header for attribute: 'version'
    major: Attribute
    minor: Can't open object
  #001: /home/hpcsoft/ProdSoft/dsk/v2.3.3-68b79e4/x86_64/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Aint.c line 433 in H5A__open(): unable to load attribute info from object header for attribute: 'version'
    major: Attribute
    minor: Can't open object
  #002: /home/hpcsoft/ProdSoft/dsk/v2.3.3-68b79e4/x86_64/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5Oattribute.c line 515 in H5O__attr_open_by_name(): can't locate attribute: 'version'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /home/hpcsoft/ProdSoft/dsk/v2.3.3-68b79e4/x86_64/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 704 in H5Aget_space(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /home/hpcsoft/ProdSoft/dsk/v2.3.3-68b79e4/x86_64/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5S.c line 1013 in H5Sget_simple_extent_dims(): not a dataspace
    major: Invalid arguments to routine
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.10.5) thread 0:
  #000: /home/hpcsoft/ProdSoft/dsk/v2.3.3-68b79e4/x86_64/thirdparty/gatb-core/gatb-core/thirdparty/hdf5/src/H5A.c line 662 in H5Aread(): not an attribute
    major: Invalid arguments to routine
    minor: Inappropriate type
---------------------------------------------

**Comment by rchikhi** [comment]
Hi, that is odd. Can you try on the provided binary? https://github.com/GATB/dsk/releases/download/v2.3.3/dsk-v2.3.3-bin-Linux.tar.gz 
or on another machine to see if you can reproduce the problem.
