### ISSUE TITLE
zero abundance k-mer list?

### ISSUE THREAD

**Issue by mikeds211** [GATB/dsk#15]
I am looking for a list of absent 6-mers in a 30kb DNA sequence. I thought this would be easy using dsk. I set the flag "-abundance-min 0"  but when I convert to text and look at the output it lists all the 6-mers with abundances down to 1 but not the zero k-mers. Why is this?

**Comment by rchikhi** [comment]
hi, sorry, DSK doesn't support reporting absent kmers. Your best bet is to use the linux command `comm` to have the set difference between the list of all possible kmers and those reported by dsk, paying also attention that dsk reports canonical output.
