### ISSUE TITLE
[bug?] the most commun kmer does not existe in file 

### ISSUE THREAD

**Issue by mewu3** [GATB/dsk#16]
Dear all, 

I have a fasta file which i would like to count 13mer of all sequences, after counting i sort the kmer according to their abundance. 
But the most commun kmer is not present in that fasta file.

**Comment by rchikhi** [comment]
maybe it's reverse complement is present

**Comment by mewu3** [comment]
Yes, that's what I figured out at the end, I have switched to KMC3 cause they have the -b option to count k-mers with only forwards reads. 
Thank you for your reply.

**Comment by rchikhi** [comment]
for the record, DSK can
