### ISSUE TITLE
Support for Compressed datatset

### ISSUE THREAD

**Issue by taranglute** [GATB/dsk#2]
Hi
I have quick query and it is related to support for compressed datatset.
Does DSK supports compressed datatset(gzip) and how to load one.

**Comment by rchikhi** [comment]
yes, it does, you can just give a gzipped file as if it was a fastq file (-in reads.fq.gz) or a list of gzipped fastq files (ls -1 *.fq.gq > list_files && ./dsk -in list_files)

**Comment by taranglute** [comment]
Thank you :+1:
