### ISSUE TITLE
-in parameter bug

### ISSUE THREAD

**Issue by rizkg** [GATB/dsk#5]
After updating the gatb-core submodule, fab3109a157c2682218e7c0f692cb060ea4cefb4 , the following command does not work : 

     dsk -file  reads.fasta 
     EXCEPTION: Empty property '-in'

Passing -in parameter does not work either : 

     dsk -in  reads.fasta 
     ERROR: Unknown parameter '-in'

**Comment by rchikhi** [comment]
thanks!

**Comment by rizkg** [comment]
sorry, that was entirely my fault :)
