### ISSUE TITLE
installing issue on MacOS

### ISSUE THREAD

**Issue by mamora** [GATB/dsk#8]
I keep getting an error after the installation:

2 warnings and 10 errors generated.
make[2]: *** [ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/gatb/template/TemplateSpecialization5.cpp.in_64.cpp.o] Error 1
2 warnings and 10 errors generated.
make[2]: *** [ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/gatb/template/TemplateSpecialization5.cpp.in_96.cpp.o] Error 1
make[1]: *** [ext/gatb-core/src/CMakeFiles/gatbcore-static.dir/all] Error 2
make: *** [all] Error 2
Running simple test...
could not find a compiled dsk binary

**Comment by rchikhi** [comment]
What was the issue?

**Comment by mamora** [comment]
I was not installing from the compiled dsk posted on the dsk website, instead I was trying to install directly from the github download files.
