### ISSUE TITLE
not all kmers are shown

### ISSUE THREAD

**Issue by mamora** [GATB/dsk#9]
I run dsk to find kmer counts for a very diverse set of reads. I notice that for a 5mer only 512 5mers are shown. Some of the kmer omitted are highly present in my reads (I know that by doing a simple find-search at a text editor).

Is there any way to show a list of all kmers and their counts? 

What I did so far is was running the following code with the latest dsk version:

./bin/dsk -file ./new_runs/positive_control_2_degenerate_f_r.txt.fasta -kmer-size 5

./bin/dsk2ascii -file ./new_runs/positive_control_2_degenerate_f_r.txt.h5 -out ./new_runs/positive_control_2_degenerate_f_r.txt

**Comment by rchikhi** [comment]
Hi, this is expected: https://github.com/GATB/dsk/blob/master/README.md#kmers-and-their-reverse-complements
Actually yes, there is a way to report the count of all kmers, separating the forward and reverse complements: compile with `cmake -DNONCANONICAL=1`
Best,
Rayan
